name: Hello workflow

on: pull_request

jobs:
  job-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step hello 1
        run: echo "step1"

      - name: Step hello 2
        run: echo "step2"